### ISSUE TITLE
Syntax error on /noia-node-terminal/node_modules/noia-governance/sdk/index.js ?

### ISSUE THREAD

**Issue by luismiparra** [noia-network/noia-node-cli#1]
**root@mydebian9:/home/noia/noia-node-terminal# npm start

> node-terminal@0.1.0 start /home/noia/noia-node-terminal
> node index

/home/noia/noia-node-terminal/node_modules/noia-governance/sdk/index.js:77
    init: async (options) => {
                ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/noia/noia-node-terminal/node_modules/noia-node/dist/lib/wallet.js:8:24)

npm ERR! Linux 4.9.0-6-amd64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.14.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! node-terminal@0.1.0 start: `node index`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-terminal@0.1.0 start script 'node index'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-terminal package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-terminal
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-terminal
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/noia/noia-node-terminal/npm-debug.lo**

**Comment by Pierozi** [comment]
Hello @luismiparra 
The `async` method used by noia are only supported on nodejs version 7.6 or superior.

The latest node version are `10.4.1`, you must upgrade your node version.

**Comment by MartynasZilinskas** [comment]
Thanks for submitting an issue. With the latest version, it should not be relevant. If an errors occurs, please open new issue.
