### ISSUE TITLE
Service error

### ISSUE THREAD

**Issue by rodrigosobrero** [noia-network/noia-node-cli#17]
There was an error when I try to run the command `systemctl start noia-node`.

![image](https://user-images.githubusercontent.com/14170432/51266372-dc67ed80-1999-11e9-821f-20a2ed7454fe.png)

**Comment by NojusLi** [comment]
there are some changes in the readme which solve this error, check it here:
https://github.com/noia-network/noia-node-cli

also, we made a tutorial:
https://goo.gl/DCyuoh
