### ISSUE TITLE
Open port for noia-node-terminal

### ISSUE THREAD

**Issue by sabelosimelane** [noia-network/noia-node-cli#3]
Is there a way to test if noia-node-terminal is able to accept incoming connections? 

Do I need to open specific ports or does the node establish connections from inside my LAN?

**Comment by BrunoShadoko** [comment]
By default it is listening on port 7676, you have to forward it to the machine that is running the client.
You can check if the port is open on several websites (search for  online port scanner to find one).

**Comment by MartynasZilinskas** [comment]
Thanks for submitting an issue. I am closing this issue, because it's not related to any problem with the latest release. If you have any problems, please open a new issue.
